# Generated by Django 5.0 on 2024-03-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cofe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название кофе')),
                ('description', models.TextField(verbose_name='Описание кофе')),
                ('image', models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Кофе',
                'verbose_name_plural': 'Кофе',
            },
        ),
    ]
