# Generated by Django 5.0 on 2024-03-15 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_cofe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cofe',
            new_name='Site',
        ),
    ]
